# Generated by Django 4.1.7 on 2023-03-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+4454546575",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "bio",
                    models.TextField(default="WHo you be?", verbose_name="About me"),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Your license",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        default="/people.jpg",
                        upload_to="",
                        verbose_name="profile image",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        verbose_name="Your gender",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="NG", max_length=75, verbose_name="country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Lagos", max_length=180, verbose_name="City"
                    ),
                ),
                (
                    "is_buyer",
                    models.BooleanField(
                        default=False, help_text="Are You a Buyer", verbose_name="Buyer"
                    ),
                ),
                (
                    "is_seller",
                    models.BooleanField(
                        default=False,
                        help_text="Are You a Seller",
                        verbose_name="Seller",
                    ),
                ),
                (
                    "is_agent",
                    models.BooleanField(
                        default=False,
                        help_text="Are You an Agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "top_agent",
                    models.BooleanField(default=False, verbose_name="Top Agent"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=1, max_digits=4, null=True
                    ),
                ),
                (
                    "num_reviews",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Reviews"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
